export enum Operator {
  Equals = 'equals',
  Contains = 'contains',
  NotEquals = 'not_equals',
  In = 'in',
  All = 'all',
  NotIn = 'not_in',
  Exists = 'exists',
  GreaterThan = 'greater_than',
  GreaterThanEqual = 'greater_than_equal',
  LessThan = 'less_than',
  LessThanEqual = 'less_than_equal',
  Like = 'like',
  NotLike = 'not_like',
  Within = 'within',
  Intersects = 'intersects',
  Near = 'near',
}
